/**
 * Deploys ZombieCoin, ZombieHero, ZombieGame to Arc Testnet, then transfers
 * ZombieCoin ownership to the ZombieGame so only the game can mint rewards.
 *
 * After running:
 *   - Addresses are written to deployments/arcTestnet.json
 *   - frontend/js/addresses.js is regenerated so the UI picks them up
 *   - ABIs are copied into frontend/abi/
 */

const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deployer:", deployer.address);
  console.log("Balance :", (await hre.ethers.provider.getBalance(deployer.address)).toString(), "wei (USDC)");

  const usdcAddress = process.env.USDC_ADDRESS;
  if (!usdcAddress || usdcAddress === "0x0000000000000000000000000000000000000000") {
    console.warn(
      "WARNING: USDC_ADDRESS is not set in .env. Paid hero mints will not work " +
      "until you set it to the real testnet USDC contract address on Arc."
    );
  }

  // The signer wallet that will sign score claims off-chain.
  // For testnet simplicity, reuse the deployer; in production use a separate key.
  const scoreSigner = process.env.SCORE_SIGNER_ADDRESS || deployer.address;
  const treasury = process.env.TREASURY_ADDRESS || deployer.address;
  const baseURI = process.env.HERO_BASE_URI || "https://example.com/hero/";

  // 1. ZombieCoin
  console.log("\nDeploying ZombieCoin ...");
  const Coin = await hre.ethers.getContractFactory("ZombieCoin");
  const coin = await Coin.deploy(deployer.address);
  await coin.waitForDeployment();
  const coinAddr = await coin.getAddress();
  console.log("  ZombieCoin :", coinAddr);

  // 2. ZombieHero
  console.log("\nDeploying ZombieHero ...");
  const Hero = await hre.ethers.getContractFactory("ZombieHero");
  const hero = await Hero.deploy(
    deployer.address,
    usdcAddress || "0x0000000000000000000000000000000000000001",
    treasury,
    baseURI
  );
  await hero.waitForDeployment();
  const heroAddr = await hero.getAddress();
  console.log("  ZombieHero :", heroAddr);

  // 3. ZombieGame
  console.log("\nDeploying ZombieGame ...");
  const Game = await hre.ethers.getContractFactory("ZombieGame");
  const game = await Game.deploy(deployer.address, coinAddr, heroAddr, scoreSigner);
  await game.waitForDeployment();
  const gameAddr = await game.getAddress();
  console.log("  ZombieGame :", gameAddr);

  // 4. Hand ZombieCoin ownership to ZombieGame so only the game can mint rewards.
  console.log("\nTransferring ZombieCoin ownership to ZombieGame ...");
  const tx = await coin.transferOwnership(gameAddr);
  await tx.wait();
  console.log("  Done. Coin owner =", await coin.owner());

  // 5. Persist outputs
  const out = {
    network: "arcTestnet",
    chainId: 5042002,
    deployer: deployer.address,
    scoreSigner,
    treasury,
    contracts: {
      ZombieCoin: coinAddr,
      ZombieHero: heroAddr,
      ZombieGame: gameAddr,
      USDC: usdcAddress || "",
    },
    deployedAt: new Date().toISOString(),
  };
  const dir = path.join(__dirname, "..", "deployments");
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "arcTestnet.json"), JSON.stringify(out, null, 2));
  console.log("\nWrote deployments/arcTestnet.json");

  // 6. Frontend addresses
  const feDir = path.join(__dirname, "..", "frontend", "js");
  fs.mkdirSync(feDir, { recursive: true });
  const addressesJs =
    `// AUTO-GENERATED by scripts/deploy.js. Do not edit manually.\n` +
    `window.ARC_DEPLOYMENT = ${JSON.stringify(out, null, 2)};\n`;
  fs.writeFileSync(path.join(feDir, "addresses.js"), addressesJs);
  console.log("Wrote frontend/js/addresses.js");

  // 7. Copy ABIs
  const abiDir = path.join(__dirname, "..", "frontend", "abi");
  fs.mkdirSync(abiDir, { recursive: true });
  const artifacts = ["ZombieCoin", "ZombieHero", "ZombieGame"];
  for (const name of artifacts) {
    const art = require(`../artifacts/contracts/${name}.sol/${name}.json`);
    fs.writeFileSync(path.join(abiDir, `${name}.json`), JSON.stringify(art.abi, null, 2));
  }
  // Minimal USDC ABI (approve + balance) for the front-end.
  const usdcAbi = [
    "function approve(address spender, uint256 value) external returns (bool)",
    "function allowance(address owner, address spender) external view returns (uint256)",
    "function balanceOf(address owner) external view returns (uint256)",
    "function decimals() external view returns (uint8)",
    "function symbol() external view returns (string)",
  ];
  fs.writeFileSync(path.join(abiDir, "USDC.json"), JSON.stringify(usdcAbi, null, 2));
  console.log("Wrote ABIs to frontend/abi/");

  console.log("\nDeployment complete. Open frontend/index.html (via `npm run serve`) to play.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
