const hre = require("hardhat");

async function main() {
  console.log("🎮 Deploying ArcLoot Game to Arc Testnet...");
  console.log("Network:", hre.network.name);
  console.log("Chain ID:", (await hre.ethers.provider.getNetwork()).chainId);

  const [deployer] = await hre.ethers.getSigners();
  console.log("Deployer:", deployer.address);

  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log("Balance:", hre.ethers.formatEther(balance), "USDC (native gas)");

  // Deploy ArcLoot contract
  const ArcLoot = await hre.ethers.getContractFactory("ArcLoot");
  const arcLoot = await ArcLoot.deploy();
  await arcLoot.waitForDeployment();

  const address = await arcLoot.getAddress();
  console.log("\n✅ ArcLoot deployed to:", address);
  console.log("Explorer:", `https://testnet.arcscan.app/address/${address}`);

  // Save deployment info
  const fs = require("fs");
  const deploymentInfo = {
    network: "Arc Testnet",
    chainId: 5042002,
    contract: "ArcLoot",
    address: address,
    deployer: deployer.address,
    timestamp: new Date().toISOString(),
    explorer: `https://testnet.arcscan.app/address/${address}`,
  };

  fs.writeFileSync(
    "deployment.json",
    JSON.stringify(deploymentInfo, null, 2)
  );
  console.log("\n📄 Deployment info saved to deployment.json");

  // Update frontend addresses
  const frontendAddresses = `// Auto-generated by deploy script
// Arc Testnet (Chain ID: 5042002)
export const CONTRACT_ADDRESS = "${address}";
export const NETWORK_CONFIG = {
  chainId: "0x4CE4F2", // 5042002 in hex
  chainName: "Arc Testnet",
  rpcUrls: ["https://rpc.testnet.arc.network"],
  blockExplorerUrls: ["https://testnet.arcscan.app"],
  nativeCurrency: {
    name: "USDC",
    symbol: "USDC",
    decimals: 18,
  },
};
`;

  fs.writeFileSync("frontend/js/config.js", frontendAddresses);
  console.log("📄 Frontend config updated");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
