// Placeholder. This file is REGENERATED by `npm run deploy:arc`.
// Until you deploy, the front-end runs in "demo mode" (game playable, no on-chain calls).
window.ARC_DEPLOYMENT = window.ARC_DEPLOYMENT || {
  network: "arcTestnet",
  chainId: 5042002,
  contracts: {
    ZombieCoin: "",
    ZombieHero: "",
    ZombieGame: "",
    USDC: ""
  }
};
